sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: abc123
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: sky-take-out-lzh
  redis:
    host: localhost
    port: 6379
    password: abc123
    database: 10
  wechat:
    appid: wx0d798af4c4c716de
    secret: 6ac1d115b5b5771e846ea55bc3d14d64